spring:
  cloud:
    stream:
      bindings:
        input:
          destination: email
          group: email-service
  mail:
    host: smtp.gmail.com
    username: emcforum2016hk
    password: PivotalCF
    port: 587
    test-connection: true
    protocol: smtp
    properties:
      mail:
        smtp.starttls.enable: true


email:
  reallySend: false
  subject: Congratulations!
  body: Congratulations! You have win the game in EMC forum 2016. You may present this email to the counter and receive a gift.